# Generated by Django 3.2.4 on 2021-06-13 12:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=2000)),
                ('Details', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
